"""changed name of user to name_of_user

Revision ID: 9695bb5413fa
Revises: bfd59a0ccefc
Create Date: 2023-08-20 13:14:48.665318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9695bb5413fa'
down_revision: Union[str, None] = 'bfd59a0ccefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_of_user', sa.String(), nullable=True))
    op.drop_column('users', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'name_of_user')
    # ### end Alembic commands ###
