"""tables are so much fun

Revision ID: ce8f466a22e5
Revises: df422d0d0ac0
Create Date: 2023-08-22 17:27:08.018700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8f466a22e5'
down_revision: Union[str, None] = 'df422d0d0ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website_name', sa.String(), nullable=True))
    op.drop_column('users', 'website')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'website_name')
    # ### end Alembic commands ###
