"""fixing tables

Revision ID: df422d0d0ac0
Revises: f8073d4f32f1
Create Date: 2023-08-22 17:21:18.824609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df422d0d0ac0'
down_revision: Union[str, None] = 'f8073d4f32f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    # ### end Alembic commands ###
