""" deleted website on user

Revision ID: f8073d4f32f1
Revises: 0a1deb80c321
Create Date: 2023-08-22 16:39:24.812262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8073d4f32f1'
down_revision: Union[str, None] = '0a1deb80c321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
